apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::760074129045:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VV9O3H4BK3YB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::760074129045:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-04T23:09:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1513"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ce3a1e0d-beaf-4b35-9005-a71a471719a9
