apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::760074129045:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6MAI853FI11A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-06T19:04:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2467"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 097421dc-83a1-431a-b11a-a140d01efaad
