apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::760074129045:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VSYEXZKG5TL0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-05T15:07:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1299"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e6ebf0ac-f305-4ca0-9c4c-33f12f196c43
