apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::760074129045:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::760074129045:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1J32GAT7GFP75
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-04T19:22:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1366"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cc0b1ab6-f807-412d-a159-f226dbbe14a1
